from __future__ import annotations

from prepos.domain.scoring.common import (
    clamp,
    logistic,
    norm,
    recency_weight,
    redistribute_weights,
    round_score,
    shrink,
    weighted_blend,
)
from prepos.domain.scoring.confidence_v1 import (
    CONFIDENCE_V1,
    ConfidenceInputs,
    ConfidenceResult,
    compute_confidence_v1,
    compute_consistency_score,
    compute_speed_score,
    map_self_assessment,
)
from prepos.domain.scoring.config import DEFAULT_SCORING_CONFIG, ScoringConfig
from prepos.domain.scoring.importance_copy_v1 import (
    IMPORTANCE_COPY_V1,
    ImportanceCopyInputs,
    ImportanceCopyResult,
    compute_importance_copy_v1,
)
from prepos.domain.scoring.mastery_nonmcq_v1 import (
    MASTERY_NONMCQ_V1,
    MasteryNonMcqResult,
    compute_mastery_nonmcq_v1,
)
from prepos.domain.scoring.mastery_v1 import (
    MASTERY_V1,
    MasteryEvidenceCounters,
    MasteryResult,
    McqAttemptEvidence,
    McqDifficulty,
    build_mastery_evidence,
    compute_mastery_v1,
    compute_mcq_component,
    compute_recency_weighted_component,
    compute_study_component,
    difficulty_multiplier,
)
from prepos.domain.scoring.readiness_drivers_v1 import (
    READINESS_DRIVERS_V1,
    ReadinessDriversV1,
    compute_readiness_drivers_v1,
)
from prepos.domain.scoring.readiness_v1 import (
    READINESS_V1,
    ReadinessExplanation,
    ReadinessInputs,
    ReadinessResult,
    compute_readiness_explanation,
    compute_readiness_v1,
)
from prepos.domain.scoring.readiness_v1_1 import (
    READINESS_V1_1,
    ReadinessInputsV1_1,
    ReadinessResultV1_1,
    compute_readiness_v1_1,
)
from prepos.domain.scoring.retention_v1 import (
    RETENTION_V1,
    RetentionInputs,
    RetentionResult,
    apply_revision_retention_update,
    compute_retention_v1,
    initialize_stability_from_mastery,
)
from prepos.domain.scoring.weakness_v1 import (
    WEAKNESS_V1,
    WeaknessInputs,
    WeaknessResult,
    compute_weakness_v1,
    is_overconfident,
)

__all__ = [
    "CONFIDENCE_V1",
    "DEFAULT_SCORING_CONFIG",
    "IMPORTANCE_COPY_V1",
    "MASTERY_NONMCQ_V1",
    "MASTERY_V1",
    "READINESS_DRIVERS_V1",
    "READINESS_V1",
    "READINESS_V1_1",
    "RETENTION_V1",
    "WEAKNESS_V1",
    "ConfidenceInputs",
    "ConfidenceResult",
    "ImportanceCopyInputs",
    "ImportanceCopyResult",
    "McqAttemptEvidence",
    "McqDifficulty",
    "MasteryEvidenceCounters",
    "MasteryNonMcqResult",
    "MasteryResult",
    "ReadinessDriversV1",
    "ReadinessExplanation",
    "ReadinessInputs",
    "ReadinessInputsV1_1",
    "ReadinessResult",
    "ReadinessResultV1_1",
    "RetentionInputs",
    "RetentionResult",
    "ScoringConfig",
    "WeaknessInputs",
    "WeaknessResult",
    "apply_revision_retention_update",
    "build_mastery_evidence",
    "clamp",
    "compute_confidence_v1",
    "compute_consistency_score",
    "compute_importance_copy_v1",
    "compute_mastery_nonmcq_v1",
    "compute_mastery_v1",
    "compute_mcq_component",
    "compute_readiness_drivers_v1",
    "compute_readiness_explanation",
    "compute_readiness_v1",
    "compute_readiness_v1_1",
    "compute_recency_weighted_component",
    "compute_retention_v1",
    "initialize_stability_from_mastery",
    "compute_speed_score",
    "compute_study_component",
    "compute_weakness_v1",
    "difficulty_multiplier",
    "is_overconfident",
    "logistic",
    "map_self_assessment",
    "norm",
    "recency_weight",
    "redistribute_weights",
    "round_score",
    "shrink",
    "weighted_blend",
]
