from __future__ import annotations

from enum import StrEnum

MENTOR_V1 = "mentor_v1"

_DUE_REVISION_HIGH_THRESHOLD = 5
_GOAL_PROBABILITY_CRITICAL = 40
_GOAL_PROBABILITY_AT_RISK = 60
_GOAL_PROBABILITY_EXCELLENT = 80
_READINESS_GOOD = 60
_READINESS_EXCELLENT = 80
_CONSISTENCY_POSITIVE_THRESHOLD = 80
_READINESS_ALERT_THRESHOLD = 50


class InsightType(StrEnum):
    READINESS_ALERT = "READINESS_ALERT"
    GOAL_RISK = "GOAL_RISK"
    REVISION_WARNING = "REVISION_WARNING"
    BEHAVIOR_WARNING = "BEHAVIOR_WARNING"
    OPTIMIZATION_OPPORTUNITY = "OPTIMIZATION_OPPORTUNITY"
    MILESTONE_ALERT = "MILESTONE_ALERT"
    POSITIVE_PROGRESS = "POSITIVE_PROGRESS"


class InsightPriority(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class OverallStatus(StrEnum):
    EXCELLENT = "EXCELLENT"
    GOOD = "GOOD"
    AT_RISK = "AT_RISK"
    CRITICAL = "CRITICAL"


class CoachingAction(StrEnum):
    COMPLETE_REVISIONS = "COMPLETE_REVISIONS"
    FOCUS_WEAKNESS_RECOVERY = "FOCUS_WEAKNESS_RECOVERY"
    INCREASE_DAILY_STUDY_TIME = "INCREASE_DAILY_STUDY_TIME"
    MAINTAIN_CURRENT_PLAN = "MAINTAIN_CURRENT_PLAN"


class MentorActionType(StrEnum):
    CONTACT_STUDENT = "CONTACT_STUDENT"
    SCHEDULE_REVIEW = "SCHEDULE_REVIEW"
    ASSIGN_REVISION_SPRINT = "ASSIGN_REVISION_SPRINT"
    INCREASE_STUDY_TARGET = "INCREASE_STUDY_TARGET"
    ESCALATE_RISK = "ESCALATE_RISK"
    NO_ACTION_REQUIRED = "NO_ACTION_REQUIRED"


class ActionUrgency(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class EscalationLevel(StrEnum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class CaseStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class CasePriority(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class CaseResolutionReason(StrEnum):
    STUDENT_CONTACTED = "STUDENT_CONTACTED"
    PLAN_UPDATED = "PLAN_UPDATED"
    RISK_REDUCED = "RISK_REDUCED"
    GOAL_ADJUSTED = "GOAL_ADJUSTED"
    FALSE_POSITIVE = "FALSE_POSITIVE"


CASE_CREATING_ACTIONS: frozenset[MentorActionType] = frozenset(
    {
        MentorActionType.ESCALATE_RISK,
        MentorActionType.CONTACT_STUDENT,
        MentorActionType.SCHEDULE_REVIEW,
    }
)
