from __future__ import annotations

from enum import StrEnum

DECISION_ENGINE_V1 = "decision_engine_v1"


class TwinDecisionType(StrEnum):
    REVISE_NOW = "REVISE_NOW"
    FOCUS_WEAKNESS = "FOCUS_WEAKNESS"
    INCREASE_DAILY_CAPACITY = "INCREASE_DAILY_CAPACITY"
    REDUCE_DAILY_CAPACITY = "REDUCE_DAILY_CAPACITY"
    MAINTAIN_PLAN = "MAINTAIN_PLAN"
    RECOVER_COVERAGE = "RECOVER_COVERAGE"
    GOAL_RECOVERY_MODE = "GOAL_RECOVERY_MODE"
